import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :lol_analytics_web, LoLAnalyticsWeb.Endpoint,
  server: true,
  http: [ip: {0, 0, 0, 0}, port: 4000],
  url: [host: "lol-analytics.kaizer.cloud", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
